_core:
  default_config_hash: oGTHatISQ_MOsyELjbo_JH3_B--ZjJNc0W4S_hcYGaE
placeholder_text: Search
theme: '0'
size: '20'
searchpage_enable: 1
searchpage_submit_not_visible: 1
input_name: keys
block_form_id: search_block_form
